### PR TITLE
Add 016

### PR DESCRIPTION
**Pull request by Luddest**
Finished all the data for 016

### CODE REVIEW

**Comment by gamehelp16** [comment]
Thank you for your contributions! There are some little problems though, so I didn't merge your PRs yet.
- Please link directly to the image file of the artwork (example: https://i.imgur.com/JGUkzjG.jpg) and not the imgur page. Also as a tip, next time you can simply add "m" before the file extension on the URL to get the thumbnail version of an image (example: https://i.imgur.com/JGUkzjGm.jpg), so you only need to upload the full resolution version.
- On line 10 of the file there are some "excess tabs". While this is very minor and won't cause any errors, but it would look better if the indentation is fixed.
- There is no need for the word "mix" on the name of the album mixes, you only need to put the name of the mix.
- Make sure that the file name has the .json extension and make sure that it is inside the /albums folder.
- This is not your mistake per se, but since you will be editing the files I think you should fix this too while you're at it: On some songs you will find that the "feat" section contains "remixed by &lt;artist>", remove those and instead add it to the end of the track title as "(&lt;artist> Remix)". For example, on the song "Peacock" by 7 Minutes Dead, the feat field should be empty and the title becomes "Peacock (Haywyre Remix)".

Oh, also I haven't really checked other PRs, but if you do the same mistakes on those PRs please fix them too.

**Comment by Luddest** [comment]
@gamehelp16 I fixed all the problems

**Comment by gamehelp16** [comment]
Please don't upload them all first, I guess. I'm gonna check the ones you have uploaded and if there are no problems then you can upload the others.

**Comment by Luddest** [comment]
@gamehelp16 The only problem i had was that i couldn't change the path to /albums. I guess you need to do that yourself.

**Comment by gamehelp16** [comment]
The link to the image file should start with i.imgur.com and not imgur.com, even though the image is still accessible using imgur.com. But I will fix it by myself so don't worry about that.

**Pull request merged**
